export const ActionType = {
    SET_PRODUCT : "SET_PRODUCT",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    ADD_TO_CART : "ADD_TO_CART",
    DELETE_CART : "DELETE_CART"
}



